# Force Xcode environment
language: objective-c

# Forces macOS 10.11
osx_image: xcode7.3

# ruby 2.0.0 fails because of encoding test.
# Tell the user to upgrade using rbenv or calabash-sandbox.
rvm:
  - 2.1.9
  - 2.2.5

script:
  - bin/ci/travis/run.sh
  # Skip XTC run on all but the latest to avoid redundant testing;
  # the ruby version is immaterial.
  - if [[ `ruby -e 'print RUBY_VERSION'` == '2.2.5' ]]; then script/ci/travis/xtc-submit-ci.rb; fi


notifications:
  email:
    recipients:
      - joshua.moody@xamarin.com
      - chris.fuentes@xamarin.com
    on_success: change
    on_failure: always
  slack:
    rooms:
      secure: j15+d9xbUbGIyX4mmTmWP4EUg13LFiyeSGoVvpjsrPyoCR78V4jqbunLON55KczLQD5ql+xBwv34x57UZhca8g74ZBulF7A5xm7oxSyOgMOB1hgf5ruEU3n8dtWvHFvuLUyreu2QYrmGPznJnEOXE0feFuDBiyp1BpTvk4gwr+4=

